# Generated by Django 3.0.5 on 2020-07-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydetector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'managed': True, 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='measurements',
            options={'managed': True, 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': True, 'verbose_name_plural': 'Patients'},
        ),
    ]
