# Generated by Django 3.0.5 on 2020-07-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydetector', '0002_auto_20200709_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
